### PR TITLE
fix: Implement emboldening primary iref entries

### LINKED ISSUE #756: Index HTML doesn't show primary index entries in bold
Traditionally, primary entries in an index are shown in bold.

The current code for xml2rfc appears to entirely ignore the primary= attribute on irefs.

This needs to be fixed together with #688, #689, #690, but maybe could receive some attention first.

### PR DESCRIPTION
**Pull request by cabo**
(with pseudocode, please fill in with proper Python incantations)

### CODE REVIEW

**Comment by cabo** [comment]
I have no easy way to test this, but that code should be it.

**Comment by MikeBishop** [comment]
I've tried the xml2rfc from this branch against the output of your index cleaning script, and not found any items with `<strong>` in the resulting HTML output.  [Here](https://github.com/ietf-tools/xml2rfc/files/8682390/rfc9114-cleaned.zip) is the file I fed to it.

(Of course, never ruling out that I'm invoking it incorrectly.)

**Comment by cabo** [comment]
Thanks!  I don't know how to test this code, so this is very welcome input.
Can you maybe explain the right way to invoke xml2rfc right out of the repo to me offline?

**Comment by kesara** [comment]
Using @MikeBishop's attached file, I the correct items with `<strong>`.
The following is the diff without and with proposed changes for HTML.
```
5370c5370
< <a href="#frame-cancel-push" class="xref">Section 7.2.3</a>; 
---
> <strong><a href="#frame-cancel-push" class="xref">Section 7.2.3</a></strong>; 
5417c5417
< <a href="#errors" class="xref">Section 8</a>; 
---
> <strong><a href="#errors" class="xref">Section 8</a></strong>; 
5430c5430
< <a href="#control-streams" class="xref">Section 6.2.1</a>; 
---
> <strong><a href="#control-streams" class="xref">Section 6.2.1</a></strong>; 
5477c5477
< <a href="#frame-data" class="xref">Section 7.2.1</a>; 
---
> <strong><a href="#frame-data" class="xref">Section 7.2.1</a></strong>; 
5526c5526
< <a href="#frame-goaway" class="xref">Section 7.2.6</a>; 
---
> <strong><a href="#frame-goaway" class="xref">Section 7.2.6</a></strong>; 
5744c5744
< <a href="#frame-headers" class="xref">Section 7.2.2</a>; 
---
> <strong><a href="#frame-headers" class="xref">Section 7.2.2</a></strong>; 
5769c5769
< <a href="#malformed" class="xref">Section 4.1.2</a>; 
---
> <strong><a href="#malformed" class="xref">Section 4.1.2</a></strong>; 
5794c5794
< <a href="#frame-max-push-id" class="xref">Section 7.2.7</a>; 
---
> <strong><a href="#frame-max-push-id" class="xref">Section 7.2.7</a></strong>; 
5815c5815
<                     <a href="#server-push" class="xref">Section 4.6</a>; 
---
>                     <strong><a href="#server-push" class="xref">Section 4.6</a></strong>; 
5858c5858
< <a href="#push-streams" class="xref">Section 6.2.2</a>; 
---
> <strong><a href="#push-streams" class="xref">Section 6.2.2</a></strong>; 
5896c5896
< <a href="#frame-push-promise" class="xref">Section 7.2.5</a>; 
---
> <strong><a href="#frame-push-promise" class="xref">Section 7.2.5</a></strong>; 
5940c5940
< <a href="#request-streams" class="xref">Section 6.1</a>; 
---
> <strong><a href="#request-streams" class="xref">Section 6.1</a></strong>; 
5964c5964
< <a href="#frame-settings" class="xref">Section 7.2.4</a>; 
---
> <strong><a href="#frame-settings" class="xref">Section 7.2.4</a></strong>; 
5998c5998
< <a href="#errors" class="xref">Section 8</a>; 
---
> <strong><a href="#errors" class="xref">Section 8</a></strong>; 

```

**Comment by cabo** [comment]
Thank you!  This looks very good.

I won't get to adding a few primary="true" to the tests today, but this should be quite straightforward.

**Comment by cabo** [comment]
I changed the emphasis to strong+em, as using only one of these is too little to stand out.  I also added tests (two <iref primary=true, one item, one subitem) but don't know how to test the tests, so please complete that.

**Review by cabo — COMMENTED** [review]
Tests look good to me.

**Review by kesara — APPROVED** [review]

**Pull request merged**
